"""
SQLAlchemy models for TrenerAI.

Tables:
- users: User accounts and profiles
- generated_trainings: Training plans generated by AI
- feedback: User feedback on generated trainings
"""
from datetime import datetime
from typing import Optional
from sqlalchemy import (
    Column, Integer, String, Float, DateTime,
    ForeignKey, Text, JSON, Enum as SQLEnum
)
from sqlalchemy.orm import relationship
from app.database.connection import Base
import enum


class DifficultyLevel(str, enum.Enum):
    EASY = "easy"
    MEDIUM = "medium"
    HARD = "hard"


class User(Base):
    """User account and profile."""
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String(255), unique=True, index=True, nullable=False)
    name = Column(String(255), nullable=True)

    # Physical profile
    age = Column(Integer, nullable=True)
    weight = Column(Float, nullable=True)  # kg
    height = Column(Float, nullable=True)  # cm

    # Training preferences
    goals = Column(Text, nullable=True)  # Free text goals
    contraindications = Column(JSON, nullable=True)  # List of health issues
    preferred_difficulty = Column(
        SQLEnum(DifficultyLevel),
        default=DifficultyLevel.MEDIUM
    )

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    trainings = relationship("GeneratedTraining", back_populates="user")

    def __repr__(self):
        return f"<User(id={self.id}, email='{self.email}')>"


class GeneratedTraining(Base):
    """Training plan generated by AI."""
    __tablename__ = "generated_trainings"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)

    # Input parameters (what the user requested)
    input_params = Column(JSON, nullable=False)
    # Example: {
    #   "participants": 1,
    #   "difficulty": "medium",
    #   "rest_time": 60,
    #   "training_mode": "circuit",
    #   "warmup_exercises": 3,
    #   "main_exercises": 10,
    #   "cooldown_exercises": 2
    # }

    # Generated plan (full LLM output)
    plan = Column(JSON, nullable=False)
    # Example: {
    #   "warmup": [...],
    #   "main": [...],
    #   "cooldown": [...],
    #   "total_duration_minutes": 45
    # }

    # Model metadata (for prompt versioning)
    model_name = Column(String(100), nullable=True)  # e.g., "gpt-4o", "llama3.2"
    prompt_version = Column(String(50), default="v1.0")

    # Retrieved context from Qdrant
    retrieved_exercises = Column(JSON, nullable=True)  # Exercise IDs used

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    user = relationship("User", back_populates="trainings")
    feedback = relationship("Feedback", back_populates="training", uselist=False)

    def __repr__(self):
        return f"<GeneratedTraining(id={self.id}, user_id={self.user_id})>"


class Feedback(Base):
    """User feedback on generated training."""
    __tablename__ = "feedback"

    id = Column(Integer, primary_key=True, index=True)
    training_id = Column(
        Integer,
        ForeignKey("generated_trainings.id"),
        nullable=False,
        unique=True,
        index=True
    )

    # Rating (1-5 stars)
    rating = Column(Integer, nullable=False)

    # Optional comment
    comment = Column(Text, nullable=True)

    # Specific feedback fields
    was_too_hard = Column(Integer, default=False)
    was_too_easy = Column(Integer, default=False)
    exercises_liked = Column(JSON, nullable=True)  # List of exercise IDs
    exercises_disliked = Column(JSON, nullable=True)  # List of exercise IDs

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    training = relationship("GeneratedTraining", back_populates="feedback")

    def __repr__(self):
        return f"<Feedback(id={self.id}, training_id={self.training_id}, rating={self.rating})>"
